### ISSUE TITLE
Cannot map dates

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-r2dbc#49]
I created entities with both java.util.Date and java.time.LocalDateTime (I actually also tried java.sql.Date and java.sql.Timestamp). Dates don't work. They don't insert. And, if I create a table with date data and run a query, the dates don't come out.

### Task List

- [x] Make an object with a LocalDateTime as one of the fields
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Make an object with a LocalDateTime as a field
2. Save or query

### Expected Behaviour

It should map a TIMESTAMP/DATETIME to LocalDateTime and a DATE to a Date

### Actual Behaviour

`Cannot decode value`

```
java.lang.IllegalArgumentException: Cannot decode value of type java.util.Date
|               	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:60)
|               	at io.r2dbc.h2.H2Row.get(H2Row.java:73)
|               	at io.micronaut.data.r2dbc.mapper.ColumnNameR2dbcResultReader.readTimestamp(ColumnNameR2dbcResultReader.java:63)
|               	at io.micronaut.data.r2dbc.mapper.ColumnNameR2dbcResultReader.readTimestamp(ColumnNameR2dbcResultReader.java:34)
|               	at io.micronaut.data.runtime.mapper.ResultReader.readDynamic(ResultReader.java:117)
|               	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:314)
|               	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:159)
|               	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations$DefaultR2dbcReactiveRepositoryOperations.lambda$findOne$5(DefaultR2dbcRepositoryOperations.java:570)
|               	at io.r2dbc.h2.H2Result.lambda$map$0(H2Result.java:67)
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.2.3
- **JDK Version:** corretto-11

### Example Application

- https://github.com/charlie-harvey/micronaut-r2dbc-bad-dates

**Comment by charlie-harvey** [comment]
I went through every single entity in tck, not one has a date. Lots of string, Long, Integer, UUID. No dates.
https://github.com/micronaut-projects/micronaut-data/tree/master/data-tck/src/main/java/io/micronaut/data/tck/entities

**Comment by charlie-harvey** [comment]
I cloned the r2dbc repo and added two entities and changed 1 test. Uses H2 because it is easiest. But I encountered the problem using MySQL. So it isn't just the H2 driver.

**Comment by graemerocher** [comment]
I believe that R2DBC supports the modern date types like `LocalDateTime` etc.

**Comment by charlie-harvey** [comment]
It does. https://github.com/mirromutth/r2dbc-mysql#data-type-mapping
As of right now I cannot tell if this driver is not working, or Micronaut. Since I get the same error with H2 and MySQL, and I get it with `Date` and `LocalDateTime`, that leads me to believe it is in Micronaut.

**Comment by charlie-harvey** [comment]
I saw there was some date work that went into the 1.0.0 release. I updated to get the 1.0.0 of micronaut-r2dbc and micronaut (and -data) 2.2.3. And it worked! Hooray! Date problems gone.

**Comment by charlie-harvey** [comment]
I was wrong. It is still broken. Dates are being inserted but retrieving them still throws the error.

```
09:54:56.849 [reactor-tcp-nio-4] DEBUG io.micronaut.data.query - Executing Query: SELECT book_.`id`,book_.`date_created`,book_.`title`,book_.`pages`,book_.`author_id` FROM `book` book_
09:54:56.862 [reactor-tcp-nio-4] ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: Cannot decode value of type class java.util.Date for 7 with collation 63
java.lang.IllegalArgumentException: Cannot decode value of type class java.util.Date for 7 with collation 63
	at dev.miku.r2dbc.mysql.codec.DefaultCodecs.decodeNormal(DefaultCodecs.java:212)
	at dev.miku.r2dbc.mysql.codec.DefaultCodecs.decode(DefaultCodecs.java:105)
	at dev.miku.r2dbc.mysql.MySqlRow.get(MySqlRow.java:67)
	at io.micronaut.data.r2dbc.mapper.ColumnNameR2dbcResultReader.readTimestamp(ColumnNameR2dbcResultReader.java:63)
	at io.micronaut.data.r2dbc.mapper.ColumnNameR2dbcResultReader.readTimestamp(ColumnNameR2dbcResultReader.java:34)
	at io.micronaut.data.runtime.mapper.ResultReader.readDynamic(ResultReader.java:117)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:443)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:159)
```

**Comment by charlie-harvey** [comment]
🎉  Thanks so much for getting to this so quickly.
